import type { SystemNode, SystemEdge } from '@/types';

export interface Template {
  id: string;
  name: string;
  description: string;
  nodes: SystemNode[];
  edges: SystemEdge[];
}

export const TEMPLATES: Template[] = [
  {
    id: 'microservices',
    name: 'Microservices',
    description: 'Client > LB > API Gateway > 3 Services > 2 DBs + Queue',
    nodes: [
      { id: 't1-1', type: 'system', position: { x: 400, y: 0 }, data: { label: 'Client', nodeType: 'client', description: 'Web/Mobile client', techStack: ['React'] } },
      { id: 't1-2', type: 'system', position: { x: 400, y: 160 }, data: { label: 'Load Balancer', nodeType: 'load-balancer', description: '', techStack: ['Nginx'] } },
      { id: 't1-3', type: 'system', position: { x: 400, y: 320 }, data: { label: 'API Gateway', nodeType: 'api-gateway', description: 'Route & auth', techStack: ['Kong'] } },
      { id: 't1-4', type: 'system', position: { x: 80, y: 520 }, data: { label: 'User Service', nodeType: 'service', description: 'User management', techStack: ['Node.js'] } },
      { id: 't1-5', type: 'system', position: { x: 380, y: 520 }, data: { label: 'Order Service', nodeType: 'service', description: 'Order processing', techStack: ['Go'] } },
      { id: 't1-9', type: 'system', position: { x: 620, y: 520 }, data: { label: 'Message Queue', nodeType: 'queue', description: '', techStack: ['RabbitMQ'] } },
      { id: 't1-6', type: 'system', position: { x: 860, y: 520 }, data: { label: 'Notification Service', nodeType: 'service', description: 'Email/SMS notifications', techStack: ['Python'] } },
      { id: 't1-7', type: 'system', position: { x: 80, y: 720 }, data: { label: 'User DB', nodeType: 'database', description: '', techStack: ['PostgreSQL'] } },
      { id: 't1-8', type: 'system', position: { x: 380, y: 720 }, data: { label: 'Order DB', nodeType: 'database', description: '', techStack: ['PostgreSQL'] } },
    ],
    edges: [
      { id: 't1-e1', source: 't1-1', target: 't1-2', type: 'system', data: { edgeType: 'rest', label: 'HTTPS' } },
      { id: 't1-e2', source: 't1-2', target: 't1-3', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't1-e3', source: 't1-3', target: 't1-4', type: 'system', data: { edgeType: 'grpc', label: '' } },
      { id: 't1-e4', source: 't1-3', target: 't1-5', type: 'system', data: { edgeType: 'grpc', label: '' } },
      { id: 't1-e5', source: 't1-3', target: 't1-6', type: 'system', data: { edgeType: 'grpc', label: '' } },
      { id: 't1-e6', source: 't1-4', target: 't1-7', type: 'system', data: { edgeType: 'db-query', label: '' } },
      { id: 't1-e7', source: 't1-5', target: 't1-8', type: 'system', data: { edgeType: 'db-query', label: '' } },
      { id: 't1-e8', source: 't1-5', target: 't1-9', sourceHandle: 'right', targetHandle: 'left', type: 'system', data: { edgeType: 'pub-sub', label: 'OrderCreated' } },
      { id: 't1-e9', source: 't1-9', target: 't1-6', sourceHandle: 'right', targetHandle: 'left', type: 'system', data: { edgeType: 'pub-sub', label: '' } },
    ],
  },
  {
    id: 'monolith',
    name: 'Monolith',
    description: 'Client > LB > Monolith Service > DB + Cache',
    nodes: [
      { id: 't2-1', type: 'system', position: { x: 300, y: 0 }, data: { label: 'Client', nodeType: 'client', description: 'Web application', techStack: ['React'] } },
      { id: 't2-2', type: 'system', position: { x: 300, y: 140 }, data: { label: 'Load Balancer', nodeType: 'load-balancer', description: '', techStack: ['Nginx'] } },
      { id: 't2-3', type: 'system', position: { x: 300, y: 280 }, data: { label: 'Monolith', nodeType: 'service', description: 'Main application server', techStack: ['Django', 'Python'] } },
      { id: 't2-4', type: 'system', position: { x: 100, y: 460 }, data: { label: 'Database', nodeType: 'database', description: 'Primary datastore', techStack: ['PostgreSQL'] } },
      { id: 't2-5', type: 'system', position: { x: 500, y: 460 }, data: { label: 'Cache', nodeType: 'cache', description: 'Session & query cache', techStack: ['Redis'] } },
    ],
    edges: [
      { id: 't2-e1', source: 't2-1', target: 't2-2', type: 'system', data: { edgeType: 'rest', label: 'HTTPS' } },
      { id: 't2-e2', source: 't2-2', target: 't2-3', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't2-e3', source: 't2-3', target: 't2-4', type: 'system', data: { edgeType: 'db-query', label: '' } },
      { id: 't2-e4', source: 't2-3', target: 't2-5', type: 'system', data: { edgeType: 'tcp', label: '' } },
    ],
  },
  {
    id: 'event-driven',
    name: 'Event-Driven',
    description: 'Producers > Event Bus > Consumers > DBs',
    nodes: [
      { id: 't3-1', type: 'system', position: { x: 120, y: 0 }, data: { label: 'Order Producer', nodeType: 'service', description: 'Publishes order events', techStack: ['Node.js'] } },
      { id: 't3-2', type: 'system', position: { x: 520, y: 0 }, data: { label: 'Payment Producer', nodeType: 'service', description: 'Publishes payment events', techStack: ['Java'] } },
      { id: 't3-3', type: 'system', position: { x: 320, y: 180 }, data: { label: 'Event Bus', nodeType: 'queue', description: 'Central event backbone', techStack: ['Apache Kafka'] } },
      { id: 't3-4', type: 'system', position: { x: 0, y: 360 }, data: { label: 'Inventory Consumer', nodeType: 'service', description: 'Updates stock levels', techStack: ['Go'] } },
      { id: 't3-5', type: 'system', position: { x: 320, y: 360 }, data: { label: 'Analytics Consumer', nodeType: 'service', description: 'Processes analytics', techStack: ['Python'] } },
      { id: 't3-6', type: 'system', position: { x: 640, y: 360 }, data: { label: 'Notification Consumer', nodeType: 'service', description: 'Sends notifications', techStack: ['Node.js'] } },
      { id: 't3-7', type: 'system', position: { x: 0, y: 540 }, data: { label: 'Inventory DB', nodeType: 'database', description: '', techStack: ['PostgreSQL'] } },
      { id: 't3-8', type: 'system', position: { x: 320, y: 540 }, data: { label: 'Analytics DB', nodeType: 'database', description: '', techStack: ['ClickHouse'] } },
    ],
    edges: [
      { id: 't3-e1', source: 't3-1', target: 't3-3', type: 'system', data: { edgeType: 'pub-sub', label: 'OrderEvents' } },
      { id: 't3-e2', source: 't3-2', target: 't3-3', type: 'system', data: { edgeType: 'pub-sub', label: 'PaymentEvents' } },
      { id: 't3-e3', source: 't3-3', target: 't3-4', type: 'system', data: { edgeType: 'pub-sub', label: '' } },
      { id: 't3-e4', source: 't3-3', target: 't3-5', type: 'system', data: { edgeType: 'pub-sub', label: '' } },
      { id: 't3-e5', source: 't3-3', target: 't3-6', type: 'system', data: { edgeType: 'pub-sub', label: '' } },
      { id: 't3-e6', source: 't3-4', target: 't3-7', type: 'system', data: { edgeType: 'db-query', label: '' } },
      { id: 't3-e7', source: 't3-5', target: 't3-8', type: 'system', data: { edgeType: 'db-query', label: '' } },
    ],
  },
  {
    id: 'client-server',
    name: 'Client-Server',
    description: 'Client > CDN > API Server > DB + Cache',
    nodes: [
      { id: 't4-1', type: 'system', position: { x: 300, y: 0 }, data: { label: 'Client', nodeType: 'client', description: 'SPA application', techStack: ['React', 'TypeScript'] } },
      { id: 't4-2', type: 'system', position: { x: 300, y: 140 }, data: { label: 'CDN', nodeType: 'cdn', description: 'Static assets & caching', techStack: ['CloudFront'] } },
      { id: 't4-3', type: 'system', position: { x: 300, y: 280 }, data: { label: 'API Server', nodeType: 'service', description: 'REST API backend', techStack: ['Express', 'Node.js'] } },
      { id: 't4-4', type: 'system', position: { x: 100, y: 460 }, data: { label: 'Database', nodeType: 'database', description: '', techStack: ['PostgreSQL'] } },
      { id: 't4-5', type: 'system', position: { x: 500, y: 460 }, data: { label: 'Cache', nodeType: 'cache', description: '', techStack: ['Redis'] } },
    ],
    edges: [
      { id: 't4-e1', source: 't4-1', target: 't4-2', type: 'system', data: { edgeType: 'rest', label: 'HTTPS' } },
      { id: 't4-e2', source: 't4-2', target: 't4-3', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't4-e3', source: 't4-3', target: 't4-4', type: 'system', data: { edgeType: 'db-query', label: '' } },
      { id: 't4-e4', source: 't4-3', target: 't4-5', type: 'system', data: { edgeType: 'tcp', label: '' } },
    ],
  },
  {
    id: 'serverless',
    name: 'Serverless',
    description: 'Client > API Gateway > Lambda Functions > DynamoDB + S3',
    nodes: [
      { id: 't5-1', type: 'system', position: { x: 300, y: 0 }, data: { label: 'Client', nodeType: 'client', description: 'Web/Mobile client', techStack: ['React'] } },
      { id: 't5-2', type: 'system', position: { x: 300, y: 160 }, data: { label: 'API Gateway', nodeType: 'api-gateway', description: 'REST API routing', techStack: ['AWS API Gateway'] } },
      { id: 't5-3', type: 'system', position: { x: 80, y: 340 }, data: { label: 'Auth Function', nodeType: 'service', description: 'Authentication handler', techStack: ['AWS Lambda', 'Node.js'] } },
      { id: 't5-4', type: 'system', position: { x: 300, y: 340 }, data: { label: 'API Function', nodeType: 'service', description: 'Business logic handler', techStack: ['AWS Lambda', 'Python'] } },
      { id: 't5-5', type: 'system', position: { x: 520, y: 340 }, data: { label: 'Worker Function', nodeType: 'service', description: 'Background processing', techStack: ['AWS Lambda', 'Go'] } },
      { id: 't5-6', type: 'system', position: { x: 180, y: 520 }, data: { label: 'DynamoDB', nodeType: 'database', description: 'NoSQL datastore', techStack: ['DynamoDB'] } },
      { id: 't5-7', type: 'system', position: { x: 440, y: 520 }, data: { label: 'S3 Bucket', nodeType: 'cdn', description: 'Object storage', techStack: ['AWS S3'] } },
    ],
    edges: [
      { id: 't5-e1', source: 't5-1', target: 't5-2', type: 'system', data: { edgeType: 'rest', label: 'HTTPS' } },
      { id: 't5-e2', source: 't5-2', target: 't5-3', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't5-e3', source: 't5-2', target: 't5-4', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't5-e4', source: 't5-2', target: 't5-5', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't5-e5', source: 't5-4', target: 't5-6', type: 'system', data: { edgeType: 'db-query', label: '' } },
      { id: 't5-e6', source: 't5-5', target: 't5-7', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't5-e7', source: 't5-3', target: 't5-6', type: 'system', data: { edgeType: 'db-query', label: '' } },
    ],
  },
  {
    id: 'data-pipeline',
    name: 'Data Pipeline',
    description: 'Data Sources > Kafka > Stream Processors > Data Warehouse + Analytics DB',
    nodes: [
      { id: 't6-1', type: 'system', position: { x: 80, y: 0 }, data: { label: 'App Events', nodeType: 'service', description: 'Application event source', techStack: ['Node.js'] } },
      { id: 't6-2', type: 'system', position: { x: 380, y: 0 }, data: { label: 'IoT Devices', nodeType: 'client', description: 'Sensor data source', techStack: ['MQTT'] } },
      { id: 't6-3', type: 'system', position: { x: 620, y: 0 }, data: { label: 'External APIs', nodeType: 'service', description: 'Third-party data ingestion', techStack: ['REST'] } },
      { id: 't6-4', type: 'system', position: { x: 340, y: 180 }, data: { label: 'Kafka', nodeType: 'queue', description: 'Event streaming platform', techStack: ['Apache Kafka'] } },
      { id: 't6-5', type: 'system', position: { x: 120, y: 380 }, data: { label: 'Stream Processor', nodeType: 'service', description: 'Real-time transformations', techStack: ['Apache Flink'] } },
      { id: 't6-6', type: 'system', position: { x: 540, y: 380 }, data: { label: 'Batch Processor', nodeType: 'service', description: 'Batch ETL jobs', techStack: ['Apache Spark'] } },
      { id: 't6-7', type: 'system', position: { x: 120, y: 560 }, data: { label: 'Data Warehouse', nodeType: 'database', description: 'Analytical storage', techStack: ['Snowflake'] } },
      { id: 't6-8', type: 'system', position: { x: 540, y: 560 }, data: { label: 'Analytics DB', nodeType: 'database', description: 'Time-series analytics', techStack: ['ClickHouse'] } },
      { id: 't6-9', type: 'system', position: { x: 340, y: 560 }, data: { label: 'Cache', nodeType: 'cache', description: 'Query result cache', techStack: ['Redis'] } },
    ],
    edges: [
      { id: 't6-e1', source: 't6-1', target: 't6-4', type: 'system', data: { edgeType: 'pub-sub', label: 'Events' } },
      { id: 't6-e2', source: 't6-2', target: 't6-4', type: 'system', data: { edgeType: 'pub-sub', label: 'Telemetry' } },
      { id: 't6-e3', source: 't6-3', target: 't6-4', type: 'system', data: { edgeType: 'pub-sub', label: 'Data' } },
      { id: 't6-e4', source: 't6-4', target: 't6-5', type: 'system', data: { edgeType: 'pub-sub', label: '' } },
      { id: 't6-e5', source: 't6-4', target: 't6-6', type: 'system', data: { edgeType: 'pub-sub', label: '' } },
      { id: 't6-e6', source: 't6-5', target: 't6-7', type: 'system', data: { edgeType: 'db-query', label: '' } },
      { id: 't6-e7', source: 't6-6', target: 't6-8', type: 'system', data: { edgeType: 'db-query', label: '' } },
      { id: 't6-e8', source: 't6-5', target: 't6-9', type: 'system', data: { edgeType: 'tcp', label: '' } },
    ],
  },
  {
    id: 'realtime-analytics',
    name: 'Real-time Analytics',
    description: 'DNS > WAF > LB > API > Kafka Stream > Search + Monitoring',
    nodes: [
      { id: 't7-1', type: 'system', position: { x: 300, y: 0 }, data: { label: 'Client', nodeType: 'client', description: 'Dashboard & SDK', techStack: ['React'] } },
      { id: 't7-2', type: 'system', position: { x: 300, y: 140 }, data: { label: 'DNS', nodeType: 'dns', description: '', techStack: ['Route 53'] } },
      { id: 't7-3', type: 'system', position: { x: 300, y: 280 }, data: { label: 'WAF', nodeType: 'waf', description: 'Rate limiting & bot protection', techStack: ['AWS WAF'] } },
      { id: 't7-4', type: 'system', position: { x: 300, y: 420 }, data: { label: 'Load Balancer', nodeType: 'load-balancer', description: '', techStack: ['ALB'] } },
      { id: 't7-5', type: 'system', position: { x: 300, y: 560 }, data: { label: 'Ingest API', nodeType: 'service', description: 'Event ingestion', techStack: ['Go'] } },
      { id: 't7-6', type: 'system', position: { x: 300, y: 720 }, data: { label: 'Kafka Stream', nodeType: 'stream', description: 'Event streaming', techStack: ['Kafka'] } },
      { id: 't7-7', type: 'system', position: { x: 80, y: 900 }, data: { label: 'Stream Processor', nodeType: 'worker', description: 'Real-time aggregation', techStack: ['Flink'] } },
      { id: 't7-8', type: 'system', position: { x: 520, y: 900 }, data: { label: 'Scheduler', nodeType: 'scheduler', description: 'Batch rollup jobs', techStack: ['Airflow'] } },
      { id: 't7-9', type: 'system', position: { x: 80, y: 1080 }, data: { label: 'Search Index', nodeType: 'search-index', description: 'Event search', techStack: ['Elasticsearch'] } },
      { id: 't7-10', type: 'system', position: { x: 520, y: 1080 }, data: { label: 'Monitoring', nodeType: 'monitoring', description: 'Metrics & alerts', techStack: ['Prometheus'] } },
    ],
    edges: [
      { id: 't7-e1', source: 't7-1', target: 't7-2', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't7-e2', source: 't7-2', target: 't7-3', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't7-e3', source: 't7-3', target: 't7-4', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't7-e4', source: 't7-4', target: 't7-5', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't7-e5', source: 't7-5', target: 't7-6', type: 'system', data: { edgeType: 'pub-sub', label: 'Events' } },
      { id: 't7-e6', source: 't7-6', target: 't7-7', type: 'system', data: { edgeType: 'pub-sub', label: '' } },
      { id: 't7-e7', source: 't7-6', target: 't7-8', type: 'system', data: { edgeType: 'pub-sub', label: '' } },
      { id: 't7-e8', source: 't7-7', target: 't7-9', type: 'system', data: { edgeType: 'db-query', label: '' } },
      { id: 't7-e9', source: 't7-8', target: 't7-10', type: 'system', data: { edgeType: 'tcp', label: '' } },
    ],
  },
  {
    id: 'serverless-fullstack',
    name: 'Serverless Fullstack',
    description: 'CDN > API Gateway > Lambda > DynamoDB + S3 + SQS + Logging',
    nodes: [
      { id: 't8-1', type: 'system', position: { x: 300, y: 0 }, data: { label: 'Client', nodeType: 'client', description: 'SPA', techStack: ['Next.js'] } },
      { id: 't8-2', type: 'system', position: { x: 300, y: 140 }, data: { label: 'CDN', nodeType: 'cdn', description: 'Static hosting', techStack: ['CloudFront'] } },
      { id: 't8-3', type: 'system', position: { x: 300, y: 280 }, data: { label: 'API Gateway', nodeType: 'api-gateway', description: '', techStack: ['AWS API Gateway'] } },
      { id: 't8-4', type: 'system', position: { x: 120, y: 440 }, data: { label: 'Auth Lambda', nodeType: 'serverless', description: 'JWT auth', techStack: ['AWS Lambda'] } },
      { id: 't8-5', type: 'system', position: { x: 480, y: 440 }, data: { label: 'API Lambda', nodeType: 'serverless', description: 'Business logic', techStack: ['AWS Lambda'] } },
      { id: 't8-6', type: 'system', position: { x: 480, y: 600 }, data: { label: 'Queue', nodeType: 'queue', description: 'Async jobs', techStack: ['SQS'] } },
      { id: 't8-7', type: 'system', position: { x: 480, y: 760 }, data: { label: 'Worker Lambda', nodeType: 'serverless', description: 'Background tasks', techStack: ['AWS Lambda'] } },
      { id: 't8-8', type: 'system', position: { x: 120, y: 620 }, data: { label: 'DynamoDB', nodeType: 'database', description: '', techStack: ['DynamoDB'] } },
      { id: 't8-9', type: 'system', position: { x: 720, y: 620 }, data: { label: 'Object Storage', nodeType: 'object-storage', description: 'File uploads', techStack: ['S3'] } },
      { id: 't8-10', type: 'system', position: { x: 720, y: 760 }, data: { label: 'Logging', nodeType: 'logging', description: 'Centralized logs', techStack: ['CloudWatch'] } },
    ],
    edges: [
      { id: 't8-e1', source: 't8-1', target: 't8-2', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't8-e2', source: 't8-2', target: 't8-3', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't8-e3', source: 't8-3', target: 't8-4', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't8-e4', source: 't8-3', target: 't8-5', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't8-e5', source: 't8-4', target: 't8-8', type: 'system', data: { edgeType: 'db-query', label: '' } },
      { id: 't8-e6', source: 't8-5', target: 't8-8', type: 'system', data: { edgeType: 'db-query', label: '' } },
      { id: 't8-e7', source: 't8-5', target: 't8-6', type: 'system', data: { edgeType: 'pub-sub', label: '' } },
      { id: 't8-e8', source: 't8-6', target: 't8-7', type: 'system', data: { edgeType: 'pub-sub', label: '' } },
      { id: 't8-e9', source: 't8-5', target: 't8-9', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't8-e10', source: 't8-7', target: 't8-10', type: 'system', data: { edgeType: 'tcp', label: '' } },
    ],
  },
  {
    id: 'kubernetes-platform',
    name: 'Kubernetes Platform',
    description: 'DNS > WAF > Ingress > K8s Cluster > Services + Monitoring + Logging',
    nodes: [
      { id: 't9-1', type: 'system', position: { x: 300, y: 0 }, data: { label: 'Client', nodeType: 'client', description: '', techStack: [] } },
      { id: 't9-2', type: 'system', position: { x: 300, y: 140 }, data: { label: 'DNS', nodeType: 'dns', description: '', techStack: ['Route 53'] } },
      { id: 't9-3', type: 'system', position: { x: 300, y: 280 }, data: { label: 'WAF', nodeType: 'waf', description: '', techStack: ['Cloudflare WAF'] } },
      { id: 't9-4', type: 'system', position: { x: 300, y: 420 }, data: { label: 'Ingress', nodeType: 'load-balancer', description: 'K8s Ingress Controller', techStack: ['Nginx Ingress'] } },
      { id: 't9-5', type: 'system', position: { x: 300, y: 580 }, data: { label: 'K8s Cluster', nodeType: 'container-cluster', description: 'Container orchestration', techStack: ['Kubernetes', 'EKS'] } },
      { id: 't9-6', type: 'system', position: { x: 80, y: 760 }, data: { label: 'API Service', nodeType: 'service', description: 'REST API pods', techStack: ['Go'] } },
      { id: 't9-7', type: 'system', position: { x: 300, y: 760 }, data: { label: 'Worker', nodeType: 'worker', description: 'Background job pods', techStack: ['Python'] } },
      { id: 't9-8', type: 'system', position: { x: 520, y: 760 }, data: { label: 'Scheduler', nodeType: 'scheduler', description: 'CronJob pods', techStack: ['Kubernetes CronJob'] } },
      { id: 't9-9', type: 'system', position: { x: 80, y: 940 }, data: { label: 'Database', nodeType: 'database', description: '', techStack: ['PostgreSQL'] } },
      { id: 't9-10', type: 'system', position: { x: 300, y: 940 }, data: { label: 'Queue', nodeType: 'queue', description: '', techStack: ['RabbitMQ'] } },
      { id: 't9-11', type: 'system', position: { x: 600, y: 580 }, data: { label: 'Monitoring', nodeType: 'monitoring', description: 'Metrics & alerts', techStack: ['Prometheus', 'Grafana'] } },
      { id: 't9-12', type: 'system', position: { x: 600, y: 760 }, data: { label: 'Logging', nodeType: 'logging', description: 'Log aggregation', techStack: ['ELK Stack'] } },
    ],
    edges: [
      { id: 't9-e1', source: 't9-1', target: 't9-2', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't9-e2', source: 't9-2', target: 't9-3', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't9-e3', source: 't9-3', target: 't9-4', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't9-e4', source: 't9-4', target: 't9-5', type: 'system', data: { edgeType: 'rest', label: '' } },
      { id: 't9-e5', source: 't9-5', target: 't9-6', type: 'system', data: { edgeType: 'grpc', label: '' } },
      { id: 't9-e6', source: 't9-5', target: 't9-7', type: 'system', data: { edgeType: 'grpc', label: '' } },
      { id: 't9-e7', source: 't9-5', target: 't9-8', type: 'system', data: { edgeType: 'grpc', label: '' } },
      { id: 't9-e8', source: 't9-6', target: 't9-9', type: 'system', data: { edgeType: 'db-query', label: '' } },
      { id: 't9-e9', source: 't9-7', target: 't9-10', type: 'system', data: { edgeType: 'pub-sub', label: '' } },
      { id: 't9-e10', source: 't9-5', target: 't9-11', type: 'system', data: { edgeType: 'tcp', label: 'Metrics' } },
      { id: 't9-e11', source: 't9-5', target: 't9-12', type: 'system', data: { edgeType: 'tcp', label: 'Logs' } },
    ],
  },
];
